import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const [animate, setAnimate] = useState(true);

  useEffect(() => {
    const handleVisibilityChange = () => {
      setAnimate(!document.hidden);
    };

    document.addEventListener("visibilitychange", handleVisibilityChange);

    return () => {
      document.removeEventListener("visibilitychange", handleVisibilityChange);
    };
  }, []);

  return (
    <>
      <Head>
        <title>AR Livings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {animate ? (
          <div className={`${styles.backgroundImage} ${animate}`} />
        ) : null}
        <div className={styles.textContainer}>
          <h2 className={styles.name}>AR Living</h2>
          <h4 className={styles.description}>
            Erleben Sie das BESTE von zwei Welten <br /> LIFESTYLE & SERVICE{" "}
            <br /> unter einem Dach
          </h4>
          <h1 className={styles.comingSoon}>COMING SOON</h1>
        </div>
      </main>
    </>
  );
}
